import random

tea_names = [
    "English Breakfast",
    "Green Tea",
    "Black Tea",
    "Chai Latte",
    "Matcha",
    "Oolong Tea",
    "Honey Lemon Tea",
    "Iced Tea",
    "Earl Grey",
    "Turmeric Tea",
    "Oat Milk Tea",
    "Lemon Tea",
    "Chamomile Tea",
    "Peppermint Tea",
    "Rose Tea",
    "Ginseng Tea",
    "Lime Tea",
    "Lemon-Adzuki Tea",
    "Matcha Latte",
    "Green Tea Latte",
    "Honey Tea",
    "Jasmine Tea",
    "Basil Tea",
    "Lavender Tea",
    "Sage Tea",
    "Rosehip Tea",
    "Black Tea",
    "Chamomile",
    "Earl Grey Tea",
    "English Tea",
    "Oolong",
    "Pu-erh Tea",
    "Matcha Green Tea",
    "White Tea",
    "Ginger Tea",
    "Peppermint",
    "Lemon Breeze Tea",
    "Mint Tea",
    "Honey Lemon",
    "Tangerine Tea",
    "Lemon Verbena Tea",
    "Green Tea Latte",
    "Earl Grey Latte",
    "Chai Tea",
    "Matcha Tea",
    "Honey Tea",
    "Lemon Tea",
    "Iced Tea",
    "Oat Milk Tea",
    "Milk Tea",
    "Coconut Tea",
    "Soda Tea"
]

print(random.choice(tea_names))
